workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter Build iOS (Debug Simulator)
        script: |
          flutter build ios --debug --simulator --no-codesign
    artifacts:
      - build/ios/iphonesimulator/*.app